services:
  mysql:
    image: mysql:8.0
    container_name: mysql_book_store
    restart: always
    environment:
      MYSQL_DATABASE: book_store
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
